### ISSUE TITLE
Got error: "No se encontró en ____ una imagen con el mismo nombre que 001."

### ISSUE THREAD

**Issue by dishuostec** [AbyszOne/Abysz-LAB-Ext#1]
Plugin version: a1b22e48
System: Ubuntu 20.04

I got an error after click DFI button:

```text
No se encontró en /home/b/Documents/tmp/controlnet-canny-abysz una imagen con el mismo nombre que 001.
Traceback (most recent call last):
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/b/stable-diffusion-webui/extensions/Abysz-LAB-Ext/scripts/Abysz_Lab.py", line 275, in main
    exit(1)
  File "/home/b/.pyenv/versions/3.10.10/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

Here's what I did:

1. Use Abysz Lab -> LAB Tools extract frames from video. 
  Video path `/home/b/Documents/tmp/origin.mp4`
  Output folder `/home/b/Documents/tmp/origin-extract`
  Fps `0`.

2. Use img2img -> Batch with ControlNet process all frames. 
  Input directory `/home/b/Documents/tmp/origin-extract`
  Output directory `/home/b/Documents/tmp/controlnet-canny`

3. Run Abysz Lab -> Main DFI with default params.
  Original frames folder `/home/b/Documents/tmp/origin-extract`
  Generated frames folder `/home/b/Documents/tmp/controlnet-canny`
  Output folder `/home/b/Documents/tmp/controlnet-canny-abysz`

I noticed that, after step2, there are many image named `frame_###.jpeg` in `/home/b/Documents/tmp/controlnet-canny`. After step3, these files are renamed to `###.jpeg` and seems sorted randomly.
In addition, after step3, there are some images in `./extensions/Abysz-LAB-Ext/scripts/Run/Source` and `./extensions/Abysz-LAB-Ext/scripts/Run/MaskD`, but `./extensions/Abysz-LAB-Ext/scripts/Run/MaskS` is empty.

**Comment by AbyszOne** [comment]
I'm not very familiar with how it works in linux, but I hope I can help you. First, confirm if you have imagemagick installed. Please confirm if there is a 001 file in the output folder.
Temporarily, you can rename your files to a 001, 002 format manually to see if it helps, and delete the run folder if the process crashes before finishing (this will be done automatically in the next update).
As a side note, getting high-quality results requires a considerable amount of experience with parameters, but I'm finishing up a new algorithm that vastly simplifies the experience and improves quality.

**Comment by AbyszOne** [comment]
Have you fixed the issue? There is a new update with several algorithm improvements and easier use.

**Comment by dishuostec** [comment]
I have tried e8236dfb just now and got a new error:

```text
Traceback (most recent call last):
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/b/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/b/stable-diffusion-webui/extensions/Abysz-LAB-Ext/scripts/Abysz_Lab.py", line 293, in main
    extra = math.ceil(extra) # redondear hacia arriba al entero más cercano
NameError: name 'math' is not defined
```

I have renamed image files, both source frames and img2img frames. It's from 001.jpeg to 183.jpeg. After run DFI, an error throwed above, and there are only 94 files in Generated frames folder. I compared these 94 files with backup, they're not the same as backup copy with the same name. Looks like they are renamed randomly.

**Comment by AbyszOne** [comment]
It looks like the latest version is not importing math. I've uploaded a fix to ensure it does. It should work now. (Tested)
What has me confused is the question of renaming. I don't have any reference to random naming, just name reading issues (like 000 or long names). Let me confirm, you say that image 007, for example, does not correspond to the seventh image in your original folder?
Sorry for the complications.

**Comment by dishuostec** [comment]
> Let me confirm, you say that image 007, for example, does not correspond to the seventh image in your original folder? 

Yes, looks like:

|Before run|After run|
|---|---|
|001.jpeg| missing |
|002.jpeg| missing |
|003.jpeg| 006.jpeg |
|004.jpeg| 007.jpeg |
|005.jpeg| 003.jpeg |
|006.jpeg| missing |
|007.jpeg| 004.jpeg |

**Comment by dishuostec** [comment]
Tried 13e95498.

```text
No se encontró en /home/b/Documents/tmp/controlnet-canny-abysz una imagen con el mismo nombre que 001.

  File "/home/b/stable-diffusion-webui/extensions/Abysz-LAB-Ext/scripts/Abysz_Lab.py", line 309, in main
```

Same as above, 89 files are missing. The name of first file "009.jpeg", so the script can't find 001.

Before run (left is Generated frames folder, right is backup):
<img width="430" alt="SCR-20230322-szmg" src="https://user-images.githubusercontent.com/384801/226930847-d226257d-4e96-4cf8-8d30-6cedc4c6a3a9.png">

After run:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/384801/226931260-841668f9-78ec-4b9f-aafd-ff00ebbf990f.png">

Compare same name:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/384801/226931556-25fa9dae-2e51-4227-af27-4e221812ae55.png">
<img width="393" alt="image" src="https://user-images.githubusercontent.com/384801/226931726-e20d9594-4c28-4135-bb35-90fa75de607d.png">

**Comment by AbyszOne** [comment]
Really disconcerting. I imagine there is something wrong with the way the rename process behaves on linux. I've uploaded a fix that might fix this. Please tell me if it is.

**Comment by dishuostec** [comment]
It seems the result of `os.listdir` is unsorted.
```python
...

files = os.listdir(source_dir)
for i, file_name in enumerate(files):
    print(file_name)
```
```bash
$ python test.py
009.jpeg
013.jpeg
089.jpeg
153.jpeg
104.jpeg
152.jpeg
079.jpeg
167.jpeg
029.jpeg
097.jpeg
109.jpeg
```

```python
...

files = sorted(os.listdir(source_dir))
for i, file_name in enumerate(files):
    print(file_name)
```
```bash
$ python test.py
001.jpeg
002.jpeg
003.jpeg
004.jpeg
005.jpeg
006.jpeg
007.jpeg
008.jpeg
009.jpeg
010.jpeg
011.jpeg
012.jpeg
```

**Comment by AbyszOne** [comment]
Yes, thats what ive corrected. It works now?

**Comment by dishuostec** [comment]
It works! I don't know much of python, I just wrapped all `os.listdir(...)` by `sorted()`.
I merged frames to a video, the direct transition between frames is not natural enough, but it's a good start.

Thank you for making this extension.

**Comment by AbyszOne** [comment]
I am glad to hear that. About the process, as it is in the guide, the objective of this process is to eliminate the abrupt changes in the originally static areas. By moving the tolerance you can control how much corruption and changes you allow. In general, the ideal is to find a reasonable balance and then remove the corruption using Stable Diffusion with the same parameters, with low denoisings to keep the original video, removing only the artifacts and defects.
I am creating a test button so that you can preview the map generated by the chosen parameters, to have a much better idea of how the process will act.
