### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by FurkanGozukara** [AbyszOne/Abysz-LAB-Ext#2]
Hello. I am trying to improve deflicking issue

Using latest version of automatic1111 and Abysz-LAB-Ext

img2img processed folder

![image](https://user-images.githubusercontent.com/19240467/227713032-864e7289-ce02-4403-af72-4313ceeeb3ad.png)

original images folder

![image](https://user-images.githubusercontent.com/19240467/227713072-708f69d4-aaa9-4c4c-8a67-b7a5459ae035.png)

everything is default because your guide is very poor unfortunately. I am trying to prepare a guide tutorial video

![image](https://user-images.githubusercontent.com/19240467/227713131-5c5ba693-ea46-4b94-b531-4126f28e0bcf.png)

And here the full error message i am getting

```
El archivo 101 ya existe. Se omite su renombre.
El archivo 102 ya existe. Se omite su renombre.
.
.
.
El archivo 1524 ya existe. Se omite su renombre.
El archivo 1525 ya existe. Se omite su renombre.
composite: unable to open image 'C:\control': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
composite: unable to open image 'net': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'net': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
composite: unable to open image 'automatic\extensions\Abysz-LAB-Ext\scripts\Run\MaskD\001.png': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'automatic\extensions\Abysz-LAB-Ext\scripts\Run\MaskD\001.png': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'C:\animation': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'C:\animation': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
composite: unable to open image 'video\abysz\001.png': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'video\abysz\001.png': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
composite: unable to open image 'net': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: unable to open image 'net': No such file or directory @ error/blob.c/OpenBlob/3537.
composite: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
composite:  `automatic\extensions\Abysz-LAB-Ext\scripts\Run\MaskS\result.png' @ error/composite.c/CompositeImageCommand/1632.
Traceback (most recent call last):
  File "C:\control net automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\control net automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\control net automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\control net automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\control net automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\control net automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\control net automatic\extensions\Abysz-LAB-Ext\scripts\Abysz_Lab.py", line 323, in main
    os.rename(os.path.join(maskS, 'result.png'), os.path.join(maskS, f"{name}.png"))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\control net automatic\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\result.png' -> 'C:\\control net automatic\\extensions\\Abysz-LAB-Ext\\scripts\\Run\\MaskS\\001.png'
```

**Comment by AbyszOne** [comment]
The error code shows that it cannot find the directory because it has spaces in its path. It is always recommended to use _ or - for folder names. Also make sure you have the imagemagick library installed.
I understand that clearer information is needed. I have written the new algorithm so that only by moving DFI strength you can get balanced initial results. I'll take the advice and focus in future updates on simplifying the understanding of the operation for the general user.
Lastly, there is a known bug regarding renaming in some cases. Just in case, make sure that your files to be processed have a 001, 002, 003 format. That will avoid any conflicts until I can solve that issue.

**Comment by FurkanGozukara** [comment]
> The error code shows that it cannot find the directory because it has spaces in its path. It is always recommended to use _ or - for folder names. Also make sure you have the imagemagick library installed. I understand that clearer information is needed. I have written the new algorithm so that only by moving DFI strength you can get balanced initial results. I'll take the advice and focus in future updates on simplifying the understanding of the operation for the general user. Lastly, there is a known bug regarding renaming in some cases. Just in case, make sure that your files to be processed have a 001, 002, 003 format. That will avoid any conflicts until I can solve that issue.

imagemagick   installed i checked

files are saved as you said and i have shown them

but i cant change all folder names it breaks things. you cant handle space characters? 

![image](https://user-images.githubusercontent.com/19240467/227746708-06ee35a7-7707-4d56-953c-ed899a3e9710.png)

**Comment by FurkanGozukara** [comment]
> The error code shows that it cannot find the directory because it has spaces in its path. It is always recommended to use _ or - for folder names. Also make sure you have the imagemagick library installed. I understand that clearer information is needed. I have written the new algorithm so that only by moving DFI strength you can get balanced initial results. I'll take the advice and focus in future updates on simplifying the understanding of the operation for the general user. Lastly, there is a known bug regarding renaming in some cases. Just in case, make sure that your files to be processed have a 001, 002, 003 format. That will avoid any conflicts until I can solve that issue.

how can i talk with you?

i have got excellent consistency all i want is reducing flickering for my tutorial video

i will also include your script if i can make it work


https://user-images.githubusercontent.com/19240467/227746754-956f0df7-ff67-4231-80b6-38907da6326f.mp4

**Comment by AbyszOne** [comment]
It will probably help you reduce that kind of flick. Regarding the folders, I'm not sure if the problem is internal or external, but you can try putting them in quotes in the textbox: "C:\path\..."
Separate issue, if you want, send me both sources and I can do the process for you. It would be a useful test, also as a comparison to your own results.

**Comment by FurkanGozukara** [comment]
> It will probably help you reduce that kind of flick. Regarding the folders, I'm not sure if the problem is internal or external, but you can try putting them in quotes in the textbox: "C:\path..." Separate issue, if you want, send me both sources and I can do the process for you. It would be a useful test, also as a comparison to your own results.

I would like to do on my pc so that I can demonstrate people

so currently extension is working on latest automatic1111?

I am changing folder paths as you said to make it work

what settings should I try could you show me example screenshot please

**Comment by AbyszOne** [comment]
Sure, what I meant was to do it myself to test how far I could go with advanced use of the tool. Only if you wanted, nothing necessary.
Is working. I've been running several tests with SDv2.1 generations with no problem, beyond minor interface issues that are failing in all extensions.

**Comment by FurkanGozukara** [comment]
> Sure, what I meant was to do it myself to test how far I could go with advanced use of the tool. Only if you wanted, nothing necessary. Is working. I've been running several tests with SDv2.1 generations with no problem, beyond minor interface issues that are failing in all extensions.

ok it started processing after folder names fix

what settings should i use?

 
![image](https://user-images.githubusercontent.com/19240467/227747370-7c3d7b70-7418-464d-b11f-8a823a4f2fff.png)


and here a video can you also test and tell me best settings?

https://user-images.githubusercontent.com/19240467/227747345-950db59e-333b-46c5-a9f1-e601efe1d81d.mp4

**Comment by FurkanGozukara** [comment]
got error after processing 101 frames :/

![image](https://user-images.githubusercontent.com/19240467/227747405-87c7201a-6e4c-4b01-9c15-f6041f56b4a9.png)

@AbyszOne 

```
 No se encontró en C:\animation_video\abyszv3 una imagen con el mismo nombre que 1000.
Traceback (most recent call last):
  File "C:\automatic_web_ui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\automatic_web_ui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\automatic_web_ui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\automatic_web_ui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\automatic_web_ui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\automatic_web_ui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\automatic_web_ui\extensions\Abysz-LAB-Ext\scripts\Abysz_Lab.py", line 311, in main
    exit(1)
  File "C:\Python3108\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Comment by AbyszOne** [comment]
Regarding the parameters, it depends on each case and the quality of the source. What I've noticed is that it's easier to understand DFI strength as a level of stiffness. The higher it is, the more rigid it will try to keep changes, which has its corruption issues, and the lower it is, the more flexible it is by allowing changes and only adjusting on a large scale. Look at the preview to see if you have general graininess. If not, you can leave denoising at 0 and move DFI. It is a relatively fast process, compared to the generation of SD. You can also select how many frames you want to process to do many tests quickly.

**Comment by AbyszOne** [comment]
Error at 100 or at 1000. Please confirm.

**Comment by FurkanGozukara** [comment]
> Error at 100 or at 1000. Please confirm.

I changed the file naming 

still error

it is at 101

here let me show

![image](https://user-images.githubusercontent.com/19240467/227747590-7042fbba-66e4-4580-9544-bcadcf7af096.png)

input folder naming

![image](https://user-images.githubusercontent.com/19240467/227747601-a3f3d3ad-ae27-4ea6-b4f0-a6d22f34eac1.png)


animated folder naming

![image](https://user-images.githubusercontent.com/19240467/227747614-05d23407-e678-421d-abe1-ad45c9969aa8.png)


output folder. stop at 101

![image](https://user-images.githubusercontent.com/19240467/227747732-cb31510d-b184-4dc1-911a-cbc8f7e3a257.png)

**Comment by AbyszOne** [comment]
Well. Thats new for me. Ive updated a fix to use 0001 name system. It may solve the issue. I still need too fix the renaming issue so make sure your names are 0001, etc after the update to make it work.

**Comment by FurkanGozukara** [comment]
> No se encontró en C:\animation_video\abyszv3 una imagen con el mismo nombre que 1000.

ok i will test it. 

also what parameters i need?

the improvement not good with default parameters or DFI Tolerance = 1

**Comment by AbyszOne** [comment]
It all depends on what you call not good. Flick, ghosting, pixelation, etc. Each aspect has parameters to deal with it. DFI 1 can be very low in most cases. If it doesn't remove enough flick, you can try raising it, not lowering it.
If you want less pixelation you can use FPD 1 to remove noise every frame. If you want softer edges, you can turn the inter blur down a bit. And so on. It depends on each context and what you want. It's generally best to use it for stabilization and then finish it off in SD at low denoising to bring back detail.

**Comment by FurkanGozukara** [comment]
> It all depends on what you call not good. Flick, ghosting, pixelation, etc. Each aspect has parameters to deal with it. DFI 1 can be very low in most cases. If it doesn't remove enough flick, you can try raising it, not lowering it. If you want less pixelation you can use FPD 1 to remove noise every frame. If you want softer edges, you can turn the inter blur down a bit. And so on. It depends on each context and what you want. It's generally best to use it for stabilization and then finish it off in SD at low denoising to bring back detail.

could you try to improve this video please? and tell me parameters 

the eyes are the biggest flickering problem


https://user-images.githubusercontent.com/19240467/227748153-fb735683-df91-4250-b072-34e481e12fd4.mp4

**Comment by AbyszOne** [comment]
I can try any test with this tool, but i need both sources to do so. Btw, fingers cross the very last fix should solve the renaming issue foor good.

**Comment by AbyszOne** [comment]
A tip, if you need the eyes to be static, they should be mostly white in the map preview. That means it detect no movement there and will try to keep they the same longer.

**Comment by FurkanGozukara** [comment]
> I can try any test with this tool, but i need both sources to do so. Btw, fingers cross the very last fix should solve the renaming issue foor good.

sure tell me your email i will send you both sources. you can email me : furkangozukara@gmail.com

**Comment by AbyszOne** [comment]
nanai.chutub@gmail.com

**Comment by FurkanGozukara** [comment]
> [nanai.chutub@gmail.com](mailto:nanai.chutub@gmail.com)

just send email sorry for the delay

**Comment by AbyszOne** [comment]
I spent a long time trying to fix the code because I had the problem that the rename was messed up to 101. I thought something was wrong in the last fix. Nothing worked. Until I realized that your files are the ones that are messed up in the first place. The order goes from 101 to 111 to 122 in terms of temporal correlation. And then it settles and messes up again. That is why the render did not maintain temporal coherence. I give up about put it in order.
Regarding stabilization. The problem with the eyes is that in 512x512 and at a distance it is difficult for the diffusion to maintain its shape over time. In those cases you can combine a detail enhancer and a noise reducer to make the line information strong before rendering. This helps most renders a lot in terms of maintaining consistency. If you want to fix it in post, this isn't a hard case as it hardly moves and an ebsynth mask would fix it, but generally speaking it's very impractical.

**Comment by FurkanGozukara** [comment]
> I spent a long time trying to fix the code because I had the problem that the rename was messed up to 101. I thought something was wrong in the last fix. Nothing worked. Until I realized that your files are the ones that are messed up in the first place. The order goes from 101 to 111 to 122 in terms of temporal correlation. And then it settles and messes up again. That is why the render did not maintain temporal coherence. I give up about put it in order. Regarding stabilization. The problem with the eyes is that in 512x512 and at a distance it is difficult for the diffusion to maintain its shape over time. In those cases you can combine a detail enhancer and a noise reducer to make the line information strong before rendering. This helps most renders a lot in terms of maintaining consistency. If you want to fix it in post, this isn't a hard case as it hardly moves and an ebsynth mask would fix it, but generally speaking it's very impractical.

Could you teach me how can I improve eyes? The rest is really consistent 

Also I noticed naming problem with automatic1111 as well. Therfore I named all starting from 1000. Otherwise batch upscale was also broken

**Comment by FurkanGozukara** [comment]
after all i couldn't utilize Abysz-LAB-Ext to improve flickering :(

here released the tutorial video

26.) Automatic1111 Web UI - PC - Free
[Video To Anime - Generate An EPIC Animation From Your Phone Recording By Using Stable Diffusion AI](https://youtu.be/kmT-z2lqEPQ)
[
![image](https://user-images.githubusercontent.com/19240467/228096548-5f6add70-ca04-4bec-8c33-24d243227532.png)
](https://youtu.be/kmT-z2lqEPQ)
