### ISSUE TITLE
Can we use Abysz-LAB-Ext for this task?

### ISSUE THREAD

**Issue by FurkanGozukara** [AbyszOne/Abysz-LAB-Ext#4]
I have folder A and I want to apply img2img to this folder
I will upscale them

Then I have folder B, this folder contains images that I want to use as controlnet net images

So I will be able to batch process a folder with img2img and controlnet together

Image names of the both folder can be same

Here what I want to achieve

Original image that I want to use as controlnet canny + hed

![image](https://user-images.githubusercontent.com/19240467/231748617-7e76393f-bd19-49c6-8bd6-50ff9a1dcbd0.png)

input img2img

![image](https://user-images.githubusercontent.com/19240467/231748084-f019864d-65d0-4915-8485-eb535bbf56f7.png)

output img2img

![image](https://user-images.githubusercontent.com/19240467/231748136-4c368cbe-1414-41ae-a815-8a9c3a72f035.png)

without controlnet this is the output

![image](https://user-images.githubusercontent.com/19240467/231748209-87d48843-ae5b-4a94-aec5-34c530f5b81a.png)

you see hands are too bad

**Comment by AbyszOne** [comment]
This is a tool to reduce general flickering in post processing. For that you must first create the video with another medium.

**Comment by FurkanGozukara** [comment]
> This is a tool to reduce general flickering in post processing. For that you must first create the video with another medium.

Thanks
