### ISSUE TITLE
Deflickers Playground

### ISSUE THREAD

**Issue by pandrani** [AbyszOne/Abysz-LAB-Ext#6]
When I try the Blend or Overlay methods in the Deflickers Playground it doesn't seem to process all the video frames in order. For example every 18 (or 38 on another run) frames is a frame from a different part of the video. It is almost like it loses the order of the frames when it combines them. This is with a video that has been extracted into 855 frames so maybe it is a limit problem or something like that???

**Comment by AbyszOne** [comment]
I uploaded a possible fix. Let me know if the update works better.

**Comment by pandrani** [comment]
Thank you! I will try it out!

**Comment by pandrani** [comment]
Looks like your change fixed it! Thanks for this and thanks for creating this extension. It is awesome work!!!
